name: CI

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'public/**'
      - 'images/**'
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'public/**'
      - 'images/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Init Name Config (Parvathirajan Natarajan)
        run: git config --global user.name "Parvathirajan Natarajan"

      - name: Init Email Config (parvathi_rajan@hotmail.com)
        run: git config --global user.email "parvathi_rajan@hotmail.com"

      - name: Install Dependencies
        run: yarn

      - name: Code Build
        run: CI=false yarn build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
